<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "diliveraddress".
 *
 * @property integer $DiliverAddressId
 * @property integer $CustomerId
 * @property integer $StateId
 * @property string $City
 * @property string $Street
 * @property string $Zipcode
 *
 * @property Orders[] $orders
 */
class Diliveraddress extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'diliveraddress';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['StateId', 'City', 'Street', 'Zipcode'], 'required'],
            [['DiliverAddressId', 'CustomerId', 'StateId'], 'integer'],
            [['City'], 'string', 'max' => 15],
            [['Street'], 'string', 'max' => 50],
            [['Zipcode'], 'string', 'max' => 12],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'DiliverAddressId' => 'Diliver Address ID',
            'CustomerId' => 'Customer ID',
            'StateId' => 'State ID',
            'City' => 'City',
            'Street' => 'Street',
            'Zipcode' => 'Zipcode',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Orders::className(), ['DiliverId' => 'DiliverAddressId']);
    }

    public function beforeSave($insert)
    {
        $this->CustomerId = $_COOKIE['id'];
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
