<?php

return [
    'adminEmail' => 'admin@example.com',
    'state'=>[
        '1'=> 'Alabama',
		'2'=> 'Alaska',
		'3'=> 'Arizona',
		'4'=> 'Arkansas',
		'5'=> 'California',
		'6'=> 'Colorado',
		'7'=> 'Connecticut',
		'8'=> 'Delaware',
		'9'=> 'Florida',
		'10'=> 'Georgia',
		'11'=> 'Hawaii',
		'12'=> 'Idaho',
		'13'=> 'Illinois',
		'14'=> 'Indiana',
		'15'=> 'Iowa',
		'16'=> 'Kansas',
		'17'=> 'Kentucky',
		'18'=> 'Louisiana',
		'19'=> 'Maine',
		'20'=> 'Maryland',
		'21'=> 'Massachusetts',
		'22'=> 'Michigan',
		'23'=> 'Minnesota',
		'24'=> 'Mississippi',
		'25'=> 'Missouri',
		'26'=> 'Montana',
		'27'=> 'Nebraska',
		'28'=> 'Nevada',
		'29'=> 'New hampshire',
		'30'=> 'New jersey',
		'31'=> 'New mexico',
		'32'=> 'New York',
		'33'=> 'North Carolina',
		'34'=> 'North Dakota',
		'35'=> 'Ohio',
		'36'=> 'Oklahoma',
		'37'=> 'Oregon',
		'38'=> 'Pennsylvania',
		'39'=> 'Rhode island',
		'40'=> 'South carolina',
		'41'=> 'South dakota',
		'42'=> 'Tennessee',
		'43'=> 'Texas',
		'44'=> 'Utah',
		'45'=> 'Vermont',
		'46'=> 'Virginia',
		'47'=> 'Washington',
		'48'=> 'West Virginia',
		'49'=> 'Wisconsin',
		'50'=> 'Wyoming',
    ],
    'domain' => 'http://test.com:8111',
    'WarehouseState'=>[
        '1'=> 'Normal',
        '2'=> 'Outage',
    ],
    'OrderState'=>[
        '1'=> 'order',
        '2'=> 'ship',
        '3'=> 'arrive',
        '4'=> 'delivered',
    ]
];
